Contact form Added
nunegabriel/personal-portfolio pull request #4
Opened 2022-08-31 09:59 UTC by nunegabriel

- A contact form was added
- I styled the contact form
- Setup HTML and CSS linters
- the form takes user input and saves it.
- Name field accepts up to 30 chars.
- Email field accepts only emails.
- All fields have placeholder text.
- Message field accepts up to 500 chars.

2022-08-31 10:44 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @nunegabriel :wave:

## Highlights :1st_place_medal:

:heavy_check_mark: Following GitHub Flow
:heavy_check_mark: Following requirements
:heavy_check_mark: Descriptive PR Title
:heavy_check_mark: Descriptive PR Summary

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_See Below Comments_

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-31 10:44 UTC, HAMMAS-SALEEM commented on index.html
> +                   <li > <button class="bton get-intouch form-button" type="submit">Get It Touch</button></li>
- [ ] Please make your **textarea** field `required` because there should be a message in the email which would be sent to you :+1:

2022-08-31 10:44 UTC, HAMMAS-SALEEM commented on index.html
> +        <div class="foot-image">
### Your Border Radius
![upper-part (copy)](https://user-images.githubusercontent.com/93039359/187659188-6602a9c5-b1db-47c8-9419-1169aefe5a4f.png)

### Your Figma Border Radius
![border-radius-figma (copy)](https://user-images.githubusercontent.com/93039359/187659111-ccbd0571-021b-460d-b2ac-187c81d5e89d.png)

- [ ] Your Border radius is more than the Figma design border radius :sob: Please make it similar to the Figma template :+1:

2022-08-31 10:44 UTC, HAMMAS-SALEEM commented on index.html
> +        <div class="foot-image">
### Your Background
![background-student](https://user-images.githubusercontent.com/93039359/187659467-5b372807-3150-4aba-806f-4cc4b55f8022.png)

### Figma Background
![background (copy)](https://user-images.githubusercontent.com/93039359/187659531-acfd8187-fb4e-415e-a5a3-82cdc600da21.png)

- [ ] Please make your background design look similar to this figma template so all the images shown in the red boxes will appear on your design as well :blush:

2022-08-31 10:44 UTC, HAMMAS-SALEEM commented on index.html
> +                   <li > <button class="bton get-intouch form-button" type="submit">Get It Touch</button></li>
### Your Contact Form on 375px Screen Size
![contact-form-figma](https://user-images.githubusercontent.com/93039359/187660912-0a55c00e-2f91-4794-b4a9-b5829d3131c8.png)

### Figma Contact Form on 375px screen size
![contact](https://user-images.githubusercontent.com/93039359/187660948-f34cf721-8442-4e97-b168-5a4e2b834f7e.png)

- [ ] Please make your contact fields look similar to the figma template. You can see that they are going out of the screen. Please fix this issue :+1:

2022-09-01 11:30 UTC, awais-amjed approved these changes
# STATUS: APPROVED 🥳

Hi @nunegabriel , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉👏🥇✨

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] Nice Design ✔️
- [x] Good code organization ✔️ 

![gif](https://media.giphy.com/media/mGK1g88HZRa2FlKGbz/giphy.gif)

## Optional suggestions

- [ ] It would be better if you can remove the spacing around your website and make it fill the width of the whole screen as shown in the Figma design.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-17 15:05 UTC, closed without merging